Update codecov.yml

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -1,19 +1,22 @@
 name: Code Coverage
 
-on: [push]
+on: 
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
 jobs:
-  upload-coverage:
+  coverage:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
+      - name: Set up Python environment
+        uses: actions/setup-python@v5
         with:
-          python-version: 3.8 
+          python-version: '3.x'
 
       - name: Install dependencies
         run: |
@@ -22,15 +25,16 @@ jobs:
           pip install pylint
           pip install -U Flask
           pip install -U flask-cors
-          pip install pytest
-          pip install pytest-cov
+          pip install pytest pytest-cov codecov
 
-      - name: Run tests and generate coverage
+      - name: Run tests and generate coverage report
+        id: pyTest
         run: |
-          cd test
-          coverage run -m -a test_search
-          coverage run -m -a tests
+          pytest --cov=. --cov-report=xml --cov-report=term || true  # Continue even if tests fail
 
-      - name: Upload coverage report to Codecov
-        run: |
-          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
+      - name: Upload coverage to Codecov
+        if: always()  # Ensure this step runs regardless of test results
+        uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: coverage.xml  # Path to the coverage report generated by pytest-cov
