Update codecov.yml

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -1,4 +1,4 @@
-name: Code Coverage
+name: Python Test and Code Coverage
 
 on: 
   push:
@@ -7,7 +7,7 @@ on:
     branches: [ "main" ]
 
 jobs:
-  coverage:
+  test_and_coverage:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -30,7 +30,8 @@ jobs:
       - name: Run tests and generate coverage report
         id: pyTest
         run: |
-          pytest --cov=. --cov-report=xml --cov-report=term || true  # Continue even if tests fail
+          pytest --cov=. --cov-report=xml --cov-report=term
+        continue-on-error: true  # Continue to the next step even if the test one fails
 
       - name: Upload coverage to Codecov
         if: always()  # Ensure this step runs regardless of test results
@@ -38,3 +39,7 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           files: coverage.xml  # Path to the coverage report generated by pytest-cov
+
+      - name: Fail the job when tests fail
+        if: ${{ steps.pyTest.outcome == 'failure' }}
+        run: exit 1
